title: James' Coffee Blog
description: A blog about drinking and brewing coffee at home.

baseurl: "https://jamesg.blog"

base_dir: ""
output: "_site"

groups:
  - posts
  - likes
  - bookmarks
  - replies
  - reposts
  - drinking
  - rsvps
  - pages
  - webmentions

auto_generate:
  - category
  - pagination
  - date_archive
  - list_page